// Generated by CoffeeScript 1.8.0
(function() {
  angular.module('angular-raf', []).factory('raf', [
    '$rootScope', function($rootScope) {
      return {
        apply: function(f) {
          return window.requestAnimationFrame(function() {
            return $rootScope.$apply(f);
          });
        },
        onRenderFrame: function(scope, cb) {
          var disconnect, render, requestId;
          requestId = void 0;
          render = function() {
            cb();
            return requestId = window.requestAnimationFrame(render);
          };
          disconnect = scope.$on('$locationChangeStart', function() {
            if (requestId) {
              window.cancelAnimationFrame(requestId);
            }
            return disconnect();
          });
          return render();
        }
      };
    }
  ]);

}).call(this);
