// Generated by CoffeeScript 1.7.1
var AngularRaf;

angular.module('angular-raf', []).service('raf', AngularRaf = (function() {
  function AngularRaf() {
    console.assert(window.requestAnimationFrame, "Your user agent doesn't provide a suitable implementation of requestAnimationFrame() !");
    console.assert(window.cancelAnimationFrame, "Your user agent doesn't provide a suitable implementation of cancelAnimationFrame() !");
  }

  AngularRaf.prototype.onRenderFrame = function(scope, cb) {
    var disconnect, render, requestId;
    requestId = void 0;
    render = function() {
      cb();
      return requestId = window.requestAnimationFrame(render);
    };
    disconnect = scope.$on('$locationChangeStart', function() {
      if (requestId) {
        window.cancelAnimationFrame(requestId);
      }
      return disconnect();
    });
    return render();
  };

  return AngularRaf;

})());
