// Generated by CoffeeScript 1.7.1
var AngularRaf;

angular.module('angular-raf', []).service('raf', AngularRaf = (function() {
  function AngularRaf() {
    this.requestAnimationFrame = window.requestAnimationFrame || window.webkitRequestAnimationFrame || window.mozRequestAnimationFrame || window.msRequestAnimationFrame;
    console.assert(this.requestAnimationFrame, "Your user agent doesn't provide a suitable implementation of requestAnimationFrame() !");
    this.cancelAnimationFrame = window.cancelAnimationFrame || window.webkitCancelAnimationFrame || window.mozCancelAnimationFrame;
    console.assert(this.cancelAnimationFrame, "Your user agent doesn't provide a suitable implementation of cancelAnimationFrame() !");
  }

  AngularRaf.prototype.onRenderFrame = function(scope, cb) {
    var disconnect, render, requestId;
    requestId = void 0;
    render = function() {
      cb();
      return requestId = this.requestAnimationFrame(render);
    };
    disconnect = scope.$on('$locationChangeStart', function() {
      if (requestId) {
        this.cancelAnimationFrame(requestId);
      }
      return disconnect();
    });
    return render();
  };

  return AngularRaf;

})());
